### ISSUE TITLE
Unable to import deck

### ISSUE THREAD

**Issue by truest-repairman** [extesy/DeckTracker#39]
When trying to import a deck, by either pasting the decklist or the URL, an error dialog appears saying, "Something went wrong. The given key was not present in the dictionary." This error never happened before the 1.0.44 update.

**Comment by extesy** [comment]
@truest-repairman Not enough information. What game? What deck url? Are you using url or plain text?

**Comment by truest-repairman** [comment]
Hi, the game is Legends. I had tried importing a couple of my own private decks and neither had worked. That goes for trying as plain text and with the URL. One such list in plain text would be: 
###monkey###
3 Execute (Set1 #437)
1 Shadowmere (Set2 #269)
3 Bruma Profiteer (Set1 #314)
1 Priest of the Moons (Set1 #50)
1 The Night Mother (Set2 #9)
3 Thieves Guild Recruit (Set1 #471)
3 Giant Bat (Set1 #538)
1 House Kinsman (Set1 #623)
2 Penitus Oculatus Agent (Set2 #23)
2 Cloudrest Illusionist (Set1 #753)
1 Moonlight Werebat (Set1 #609)
1 The Black Dragon (Set2 #275)
2 Vicious Dreugh (Set1 #359)
1 Ahnassi (Set1 #661)
2 Knight of the Hour (Set2 #342)
3 Piercing Javelin (Set1 #659)
2 Protector of the Mane (Set999 #82)
3 Altar of Despair (Set999 #113)
2 Golden Saint (Set1 #296)
1 Immolating Blast (Set1 #754)
1 Quin'rawl Burglar (Set1 #32)
1 Senche-Tiger (Set1 #77)
2 Chaurus Reaper (Set1 #734)
1 Dawn's Wrath (Set1 #408)
2 Eclipse Baroness (Set2 #263)
3 Mantikora (Set1 #409)
1 Miraak, Dragonborn (Set1 #751)
1 Odahviing (Set1 #768)

I just tried importing a random public decklist from legends-decks and got a different bug. No error dialog appeared, but the deck that it created, intended to be an archer deck, contained three colors. It had 3 copies of Marked Man in it, which is yellow. I imported this deck twice and got the same results both times.
here is the plain text imported from https://www.legends-decks.com/deck/11617/ikarus-midrange-archer-27-2-gauntlet
###Ikarus - Midrange Archer (27-2 gauntlet)###
3 Curse (Set1 #508)
3 Rapid Shot (Set1 #757)
2 Shadow Shift (Set1 #58)
2 Daring Cutpurse (Set1 #510)
3 Fighters Guild Recruit (Set1 #472)
1 Finish Off (Set1 #505)
3 Goblin Skulk (Set1 #459)
3 Mournhold Traitor (Set1 #264)
1 Astrid (Set2 #12)
3 Morkul Gatekeeper (Set1 #105)
2 Sanctuary Pet (Set2 #20)
3 Skaven Pyromancer (Set1 #143)
3 Earthbone Spinner (Set1 #8)
1 Garnag, Dark Adherent (Set2 #21)
2 Murkwater Shaman (Set1 #460)
1 Reive, Blademaster (Set1 #591)
2 Blood Dragon (Set1 #646)
3 Cliff Racer (Set1 #434)
3 Leaflurker (Set1 #277)
2 Triumphant Jarl (Set1 #183)
3 Belligerent Giant (Set1 #401)
1 Tazkad the Packmaster (Set1 #595)

Instead, I end up with this: http://picpaste.com/pics/udt-bug-9Mux8PON.1498588658.jpg

Is there any other information I can give that you can use?

**Comment by extesy** [comment]
Thanks for the report! I don't take set number into account when importing cards so the wrong cards are imported in some cases.

**Comment by extesy** [comment]
@truest-repairman Please try version `1.0.45`, the problem should be fixed now.

**Comment by truest-repairman** [comment]
Thanks very much for your work on this. The problem that created the tri-color deck is indeed fixed. The first problem still exists however. I was able to import one of my own private decks but the one I listed above, entitled monkey, still gives me the error that a given key was not in the dictionary. Gonna play around with removing individual cards from the deck one by one for a while in case this is the same type of problem as the one you just solved.

**Comment by truest-repairman** [comment]
Here's another list that was giving me trouble:
###slay###
3 Arrow in the Knee (Set1 #793)
3 Brotherhood Sanctuary (Set2 #324)
3 Shadow Shift (Set1 #58)
3 Dune Stalker (Set1 #42)
3 Fighters Guild Recruit (Set1 #472)
3 Finish Off (Set1 #505)
3 Wind Keep Spellsword (Set1 #567)
1 Astrid (Set2 #12)
3 Brotherhood Slayer (Set2 #253)
2 Dune Smuggler (Set1 #93)
3 Skooma Racketeer (Set1 #117)
2 Archein Venomtongue (Set1 #627)
3 Cursed Spectre (Set1 #644)
3 Falkreath Defiler (Set2 #257)
1 Lucien Lachance (Set1 #776)
3 Shadowfen Priest (Set1 #526)
1 Thorn Histmage (Set1 #208)
1 Cicero the Betrayer (Set2 #716)
1 Quin'rawl Burglar (Set1 #32)
2 Eclipse Baroness (Set2 #263)
1 Blood Magic Lord (Set1 #705)
1 Night Talon Lord (Set1 #706)
1 Gravesinger (Set2 #278)

I compared this slay deck to the monk deck and the first card they had in common was The Night Mother. After removing it from the slay deck the slay deck imported correctly. The monk deck still did not import correctly though, but I'd assume it's the same problem and that another card in the list is the culprit?

**Comment by truest-repairman** [comment]
Okay, new bug. The updated version now seems to dislike that neutral cards are being counted as their own color. So the new error for three colors in a deck appears with, for example, green, yellow, and neutral cards in the deck.

**Comment by extesy** [comment]
Ah, I see, let me fix that in a moment.

**Comment by extesy** [comment]
@truest-repairman Can you try `1.0.46`?

**Comment by truest-repairman** [comment]
The Night Mother card now works and the slay deck imports perfectly. The monk deck still has problems. More than two cards look to have problems. Ahnassi and Mantikora look like they're not importing correctly ("Something went wrong. The given key was not present in the dictionary"), and I haven't figured out which other cards are throwing that but I'm narrowing it down.

**Comment by extesy** [comment]
@truest-repairman can you please give me links to decks that have these problems?

**Comment by truest-repairman** [comment]
I've been messing around with it as I test individual cards. the list below is as close as I've gotten to the original that works.
###monkey###
3 Curse (Set1 #508)
1 Arrow in the Knee (Set1 #793)
1 Brotherhood Sanctuary (Set2 #324)
3 Execute (Set1 #437)
3 Shadow Shift (Set1 #58)
3 Bruma Profiteer (Set1 #314)
1 Daring Cutpurse (Set1 #510)
1 Priest of the Moons (Set1 #50)
1 The Night Mother (Set2 #9)
3 Thieves Guild Recruit (Set1 #471)
3 Giant Bat (Set1 #538)
1 House Kinsman (Set1 #623)
2 Penitus Oculatus Agent (Set2 #23)
2 Cloudrest Illusionist (Set1 #753)
3 Moonlight Werebat (Set1 #609)
1 The Black Dragon (Set2 #275)
2 Knight of the Hour (Set2 #342)
3 Piercing Javelin (Set1 #659)
2 Protector of the Mane (Set999 #82)
2 Golden Saint (Set1 #296)
1 Immolating Blast (Set1 #754)
1 Quin'rawl Burglar (Set1 #32)
1 Senche-Tiger (Set1 #77)
2 Chaurus Reaper (Set1 #734)
1 Dawn's Wrath (Set1 #408)
3 Eclipse Baroness (Set2 #263)

the following three cards, when added to the above, caused the error. Still going through other cards to check for others.
1 Ahnassi (Set1 #661)
1 Mantikora (Set1 #409)
1 Miraak, Dragonborn (Set1 #751)

**Comment by truest-repairman** [comment]
Okay, no other cards caused a problem. the original list just for clarification since this thread has so many now is this one:
###monkey###
3 Execute (Set1 #437)
1 Shadowmere (Set2 #269)
3 Bruma Profiteer (Set1 #314)
1 Priest of the Moons (Set1 #50)
1 The Night Mother (Set2 #9)
3 Thieves Guild Recruit (Set1 #471)
3 Giant Bat (Set1 #538)
1 House Kinsman (Set1 #623)
2 Penitus Oculatus Agent (Set2 #23)
2 Cloudrest Illusionist (Set1 #753)
1 Moonlight Werebat (Set1 #609)
1 The Black Dragon (Set2 #275)
2 Vicious Dreugh (Set1 #359)
1 Ahnassi (Set1 #661)
2 Knight of the Hour (Set2 #342)
3 Piercing Javelin (Set1 #659)
2 Protector of the Mane (Set999 #82)
3 Altar of Despair (Set999 #113)
2 Golden Saint (Set1 #296)
1 Immolating Blast (Set1 #754)
1 Quin'rawl Burglar (Set1 #32)
1 Senche-Tiger (Set1 #77)
2 Chaurus Reaper (Set1 #734)
1 Dawn's Wrath (Set1 #408)
2 Eclipse Baroness (Set2 #263)
3 Mantikora (Set1 #409)
1 Miraak, Dragonborn (Set1 #751)
1 Odahviing (Set1 #768)

all but the three cards, 
1 Ahnassi (Set1 #661)
1 Mantikora (Set1 #409)
1 Miraak, Dragonborn (Set1 #751)
are working. Thanks again for spending so much time on this. How can I donate toward your work?

**Comment by extesy** [comment]
I hope it's finally fixed in `1.0.47`. I've tried all your decks and didn't get any errors. Can you please confirm?

As for donations, I haven't set up any donations yet. I'm not sure what's the most convenient way to set it up - maybe patreon would work? I've seen Gwent people use it.
